In [2]:
# we have discussed linear regression and error optimization
#polynomial regression
#y=m1x1+m1x2+m3x3+c     equation of linear regression
#y=a+bx+cx**2+dx***3   equation of polynomial regression
#we have to find best possible curve passing through data
#

In [3]:
import numpy as np
X=np.array([3.1,4.3,7.4,8.5,10.3]).reshape(-1,1)
Y=np.array([2.2,4.3,6.7,8.9,9]).reshape(-1,1)



In [4]:
from sklearn.preprocessing import PolynomialFeatures   #for data preprocessing
pol=PolynomialFeatures(degree=4)
x_pol=pol.fit_transform(X)
x_pol



array([[1.00000000e+00, 3.10000000e+00, 9.61000000e+00, 2.97910000e+01,
        9.23521000e+01],
       [1.00000000e+00, 4.30000000e+00, 1.84900000e+01, 7.95070000e+01,
        3.41880100e+02],
       [1.00000000e+00, 7.40000000e+00, 5.47600000e+01, 4.05224000e+02,
        2.99865760e+03],
       [1.00000000e+00, 8.50000000e+00, 7.22500000e+01, 6.14125000e+02,
        5.22006250e+03],
       [1.00000000e+00, 1.03000000e+01, 1.06090000e+02, 1.09272700e+03,
        1.12550881e+04]])

In [5]:
#here single feature will be converted into multiple feature
#Yp will be non linear relation of X 

In [6]:
coe=np.array([1,3.2,4.5]).reshape(3,1) 
coe

array([[1. ],
       [3.2],
       [4.5]])

In [7]:
Yp=np.dot(x_pol,coe)   #Yp calculated based upon polynomial features

ValueError: shapes (5,5) and (3,1) not aligned: 5 (dim 1) != 3 (dim 0)

In [8]:
 import matplotlib.pyplot as plt
plt.plot(X,Yp)
plt.scatter(X,Y)
plt.show()   #huge difference between real and Predicted values
#this huge difference can be decreased by optimising the value of coefficient

NameError: name 'Yp' is not defined

In [ ]:
#this error can be decreased by optimising the value of coefficinet
#we have used random coefficient Now
#we hav to optimize the coefficient to reduce error 

In [ ]:
from sklearn.linear_model import LinearRegression
lmodel=LinearRegression()
lmodel.fit(x_pol,Y)

In [9]:
Yp=lmodel.predict(x_pol)
Yp

NameError: name 'lmodel' is not defined

In [10]:
import matplotlib.pyplot as plt
plt.plot(X,Yp)
plt.scatter(X,Y)
plt.show()   #very less difference between real and Predicted values
#this less difference can be decreased by tunig the degree

NameError: name 'Yp' is not defined

In [11]:
a=np.arange(3,10).reshape(-1,1)
a   #to predict over a we need polynomial features
a_pol=pol.fit_transform(a)
a_pol
b=lmodel.predict(a_pol)
b    #predicting values

NameError: name 'lmodel' is not defined

In [12]:
import matplotlib.pyplot as plt
plt.plot(X,Yp,c='r')#line drawn over given data
plt.plot(a,b,c='g') #line drawn over unknown data
plt.scatter(X,Y)
plt.show()

NameError: name 'Yp' is not defined

In [13]:
p=np.arange(10).reshape(-1,1)
p

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [14]:
pol.fit(p)   #calculating value
pol.transform(p)   #showing or printing value

array([[1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 2.000e+00, 4.000e+00, 8.000e+00, 1.600e+01],
       [1.000e+00, 3.000e+00, 9.000e+00, 2.700e+01, 8.100e+01],
       [1.000e+00, 4.000e+00, 1.600e+01, 6.400e+01, 2.560e+02],
       [1.000e+00, 5.000e+00, 2.500e+01, 1.250e+02, 6.250e+02],
       [1.000e+00, 6.000e+00, 3.600e+01, 2.160e+02, 1.296e+03],
       [1.000e+00, 7.000e+00, 4.900e+01, 3.430e+02, 2.401e+03],
       [1.000e+00, 8.000e+00, 6.400e+01, 5.120e+02, 4.096e+03],
       [1.000e+00, 9.000e+00, 8.100e+01, 7.290e+02, 6.561e+03]])

In [15]:
lmodel.coef_  
#best coefficent calculated by model using gradient descent

NameError: name 'lmodel' is not defined

In [16]:
lmodel.coef_

NameError: name 'lmodel' is not defined

In [17]:
#for two features equation will be like Y=a+bx1+cx2+dX1**2+ex2*x1
#we have to generate those polynomial features


In [18]:
p=np.arange(10).reshape(5,2)
p

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
ppol=PolynomialFeatures(degree=2)
ppol.fit_transform(p)
#these polynomial features will be used 

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.],
       [ 1.,  6.,  7., 36., 42., 49.],
       [ 1.,  8.,  9., 64., 72., 81.]])

In [20]:
import pandas as pd
house=pd.read_csv('Housing_Data.csv')
house.head()   
#working on housing data 


Unnamed: 0    price  lotsize  bedrooms  bathrms  stories driveway recroom  \
0           1  42000.0     5850         3        1        2      yes      no   
1           2  38500.0     4000         2        1        1      yes      no   
2           3  49500.0     3060         3        1        1      yes      no   
3           4  60500.0     6650         3        1        2      yes     yes   
4           5  61000.0     6360         2        1        1      yes      no   

  fullbase gashw airco  garagepl prefarea  
0      yes    no    no         1       no  
1       no    no    no         0       no  
2       no    no    no         0       no  
3       no    no    no         0       no  
4       no    no    no         0       no

In [21]:
house.columns


Index(['Unnamed: 0', 'price', 'lotsize', 'bedrooms', 'bathrms', 'stories',
       'driveway', 'recroom', 'fullbase', 'gashw', 'airco', 'garagepl',
       'prefarea'],
      dtype='object')

In [22]:
X = house[['price','bedrooms', 'bathrms', 'stories','driveway', 'recroom']]
Y = house['lotsize']


In [23]:
X['driveway'] = X['driveway'].map({'yes':1,'no':0})
X['recroom'] = X['recroom'].map({'yes':1,'no':0})

C:\Users\harsh\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\harsh\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [24]:
X

price  bedrooms  bathrms  stories  driveway  recroom
0     42000.0         3        1        2         1        0
1     38500.0         2        1        1         1        0
2     49500.0         3        1        1         1        0
3     60500.0         3        1        2         1        1
4     61000.0         2        1        1         1        0
..        ...       ...      ...      ...       ...      ...
541   91500.0         3        2        4         1        1
542   94000.0         3        2        4         1        0
543  103000.0         3        2        4         1        1
544  105000.0         3        2        2         1        1
545  105000.0         3        1        2         1        0

[546 rows x 6 columns]

In [25]:
from sklearn.linear_model import LinearRegression
lmodel = LinearRegression()

In [26]:
lmodel.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
yp=lmodel.predict(X)

In [28]:
from sklearn import metrics
metrics.mean_absolute_error(Y,yp)

1286.5669493455134

In [29]:
metrics.mean_squared_error(Y,yp)

3123898.899458308

In [30]:
from sklearn.preprocessing import PolynomialFeatures
pol = PolynomialFeatures(degree = 2)
x_pol = pol.fit_transform(X)

In [31]:
lpmodel = LinearRegression()
lpmodel.fit(x_pol,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
ypp=lpmodel.predict(x_pol)
metrics.mean_absolute_error(Y,ypp)

1183.3485090878085

In [55]:
#reduce the features
#dimensionality reduction
#there are six features and u convert them to 2 features
#as price a lot effecting the result we would standarize the data 
from sklearn.preprocessing import StandardScaler
scl=StandardScaler()
XS=scl.fit_transform(X)
pd.DataFrame(XS)
#output is not single features dependent


0         1         2         3        4         5
0   -0.979136  0.047235 -0.569495  0.221704  0.40519 -0.464796
1   -1.110329 -1.310147 -0.569495 -0.931157  0.40519 -0.464796
2   -0.698008  0.047235 -0.569495 -0.931157  0.40519 -0.464796
3   -0.285686  0.047235 -0.569495  0.221704  0.40519  2.151480
4   -0.266944 -1.310147 -0.569495 -0.931157  0.40519 -0.464796
..        ...       ...       ...       ...      ...       ...
541  0.876311  0.047235  1.423737  2.527427  0.40519  2.151480
542  0.970020  0.047235  1.423737  2.527427  0.40519 -0.464796
543  1.307374  0.047235  1.423737  2.527427  0.40519  2.151480
544  1.382342  0.047235  1.423737  0.221704  0.40519  2.151480
545  1.382342  0.047235 -0.569495  0.221704  0.40519 -0.464796

[546 rows x 6 columns]

In [56]:
from sklearn.linear_model import LinearRegression
smodel = LinearRegression()

In [57]:
from sklearn.preprocessing import PolynomialFeatures
pol = PolynomialFeatures(degree = 2)
x_pol = pol.fit_transform(XS)

In [58]:
smodel.fit(x_pol,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [59]:
yp=smodel.predict(x_pol)
metrics.mean_absolute_error(Y,yp)

1183.0352564102564

In [79]:
XS=pd.DataFrame(XS)
XS.corr()
#correlation matrix tells about 
#correlation of feature 1 wrt every other features
#c(f1,f1)==1 all diagnol places are 1
#(f3,f1) is highest means ther are highly corelated  we can ignore them
#(f3,f2)==-ve means they are inversely related  we can't ignore them


0         1         2         3         4         5
0  1.000000  0.366447  0.516719  0.421190  0.297167  0.254960
1  0.366447  1.000000  0.373769  0.407974 -0.011996  0.080492
2  0.516719  0.373769  1.000000  0.324066  0.041955  0.126892
3  0.421190  0.407974  0.324066  1.000000  0.122499  0.042281
4  0.297167 -0.011996  0.041955  0.122499  1.000000  0.091959
5  0.254960  0.080492  0.126892  0.042281  0.091959  1.000000

In [77]:
#difference between fit and fit_transform

#fit calculates parameter 
#transform prints that
#choosing degree depends upon error values


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [78]:
#tommorow we will do dimension  reduction
#to work with same dimension
