In [1]:
import numpy as np
x1 = np.random.randint(3,15,10)
x2 = np.random.randint(5,20,10)
x3 = np.random.randint(2,19,10)

In [2]:
X = np.array([x1,x2,x3])
X = X.T
X

array([[12,  5,  4],
       [12,  8, 14],
       [13, 17,  3],
       [13,  6, 11],
       [14, 14, 18],
       [13, 19,  8],
       [10,  5, 10],
       [ 3,  8, 17],
       [14, 11, 10],
       [12, 10, 13]])

In [3]:
Y = 3*x1 + 5*x2 + 4.3*x3
Y = Y.reshape(-1,1)
Y

array([[ 78.2],
       [136.2],
       [136.9],
       [116.3],
       [189.4],
       [168.4],
       [ 98. ],
       [122.1],
       [140. ],
       [141.9]])

In [5]:
m = np.array([np.random.rand(1),
              np.random.randn(1),
              np.random.rand(1)])
m

array([[0.90328954],
       [0.41217544],
       [0.03768917]])

In [6]:
X

array([[12,  5,  4],
       [12,  8, 14],
       [13, 17,  3],
       [13,  6, 11],
       [14, 14, 18],
       [13, 19,  8],
       [10,  5, 10],
       [ 3,  8, 17],
       [14, 11, 10],
       [12, 10, 13]])